#!/bin/bash
code --install-extension robertohuertasm.vscode-icons
code --install-extension rbbit.typescript-hero
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension smlombardi.slime
code --install-extension daylerees.rainglow
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension felixfbecker.php-debug
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension christian-kohler.path-intellisense
code --install-extension PKief.material-icon-theme
code --install-extension zignd.html-css-class-completion
code --install-extension wix.vscode-import-cost
code --install-extension eamodio.gitlens
code --install-extension dbaeumer.vscode-eslint
code --install-extension mikestead.dotenv
code --install-extension peterjausovec.vscode-docker
code --install-extension coenraads.bracket-pair-colorizer
code --install-extension steoates.autoimport
code --install-extension formulahendry.auto-rename-tag
code --install-extension mrmlnc.vscode-scss
code --install-extension octref.vetur
code --install-extension Angular.ng-template
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension leizongmin.node-module-intellisense
code --install-extension robinbentley.sass-indented
code --install-extension vincaslt.highlight-matching-tag